# Generated by Django 5.0.14 on 2026-02-22 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier_nom",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="imports/shapefiles/", verbose_name="Fichier ZIP"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("COMPLETED", "Termine"),
                            ("FAILED", "Echoue"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "mapping_colonnes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Mapping des colonnes"
                    ),
                ),
                (
                    "colonnes_detectees",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Colonnes detectees"
                    ),
                ),
                (
                    "nombre_features",
                    models.IntegerField(default=0, verbose_name="Nombre de features"),
                ),
                (
                    "nombre_importees",
                    models.IntegerField(default=0, verbose_name="Features importees"),
                ),
                (
                    "nombre_erreurs",
                    models.IntegerField(default=0, verbose_name="Erreurs"),
                ),
                (
                    "rapport",
                    models.TextField(blank=True, default="", verbose_name="Rapport"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session d'import",
                "verbose_name_plural": "Sessions d'import",
                "ordering": ["-created_at"],
            },
        ),
    ]
