# Generated by Django 5.0.14 on 2026-02-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequeteNLP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte_requete", models.TextField(verbose_name="Requete utilisateur")),
                (
                    "entites_extraites",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Entites extraites"
                    ),
                ),
                (
                    "filtre_orm",
                    models.TextField(
                        blank=True, default="", verbose_name="Filtre ORM genere"
                    ),
                ),
                (
                    "nombre_resultats",
                    models.IntegerField(default=0, verbose_name="Nombre de resultats"),
                ),
                (
                    "temps_traitement_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Temps de traitement (ms)"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="ID de session",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Requete NLP",
                "verbose_name_plural": "Requetes NLP",
                "ordering": ["-created_at"],
            },
        ),
    ]
