# Generated by Django 5.0.14 on 2026-02-22 05:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NomenclatureCouvert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Code"),
                ),
                (
                    "libelle_fr",
                    models.CharField(max_length=100, verbose_name="Libelle francais"),
                ),
                (
                    "stock_carbone_reference",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Stock carbone reference (tCO2/ha)",
                    ),
                ),
                (
                    "couleur_hex",
                    models.CharField(
                        help_text="Format #RRGGBB",
                        max_length=7,
                        verbose_name="Couleur (hex)",
                    ),
                ),
                (
                    "ordre_affichage",
                    models.IntegerField(
                        default=0, verbose_name="Ordre dans la legende"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nomenclature de couvert",
                "verbose_name_plural": "Nomenclatures de couvert",
                "ordering": ["ordre_affichage"],
            },
        ),
        migrations.CreateModel(
            name="ZoneEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "type_zone",
                    models.CharField(
                        choices=[
                            ("DEPARTEMENT", "Departement"),
                            ("SOUS_PREFECTURE", "Sous-prefecture"),
                            ("LOCALITE", "Localite"),
                            ("CHEF_LIEU", "Chef-lieu"),
                        ],
                        default="DEPARTEMENT",
                        max_length=50,
                        verbose_name="Type de zone",
                    ),
                ),
                (
                    "niveau",
                    models.IntegerField(
                        default=1,
                        help_text="Niveau hierarchique (1=Departement, 2=S/P, 3=Localite)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometrie"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zone d'etude",
                "verbose_name_plural": "Zones d'etude",
                "ordering": ["niveau", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ForetClassee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom complet")),
                (
                    "superficie_legale_ha",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Superficie legale (ha)"
                    ),
                ),
                (
                    "statut_juridique",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Statut juridique",
                    ),
                ),
                (
                    "date_classement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de classement"
                    ),
                ),
                (
                    "autorite_gestion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Autorite de gestion",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometrie"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Foret classee",
                "verbose_name_plural": "Forets classees",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="carbone_for_code_185500_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_infra",
                    models.CharField(
                        choices=[
                            ("ROUTE", "Route"),
                            ("HYDROGRAPHIE", "Hydrographie"),
                            ("CHEF_LIEU_DEPT", "Chef-lieu Departement"),
                            ("CHEF_LIEU_SP", "Chef-lieu Sous-prefecture"),
                            ("LOCALITE", "Localite"),
                        ],
                        max_length=50,
                        verbose_name="Type d'infrastructure",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Nom"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Categorie"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="Geometrie"
                    ),
                ),
                (
                    "donnees",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Donnees supplementaires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Infrastructure",
                "verbose_name_plural": "Infrastructures",
                "ordering": ["type_infra", "nom"],
                "indexes": [
                    models.Index(
                        fields=["type_infra"], name="carbone_inf_type_in_bcb3f6_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Placette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_placette",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Code placette",
                    ),
                ),
                (
                    "annee_mesure",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Annee de mesure"
                    ),
                ),
                (
                    "type_foret_observe",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Type de foret observe",
                    ),
                ),
                (
                    "biomasse_tonne_ha",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Biomasse (t/ha)"
                    ),
                ),
                (
                    "stock_carbone_mesure",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Stock carbone mesure (tCO2/ha)",
                    ),
                ),
                (
                    "donnees",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Donnees supplementaires"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Geometrie"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "foret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placettes",
                        to="carbone.foretclassee",
                        verbose_name="Foret classee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Placette",
                "verbose_name_plural": "Placettes",
            },
        ),
        migrations.CreateModel(
            name="OccupationSol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.SmallIntegerField(
                        choices=[(1986, "1986"), (2003, "2003"), (2023, "2023")],
                        verbose_name="Annee d'observation",
                    ),
                ),
                (
                    "superficie_ha",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Superficie (ha)"
                    ),
                ),
                (
                    "stock_carbone_calcule",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Stock carbone (tCO2/ha)"
                    ),
                ),
                (
                    "source_donnee",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Source des donnees",
                    ),
                ),
                (
                    "fiabilite_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Fiabilite (%)"
                    ),
                ),
                (
                    "notes_admin",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometrie"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "foret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupations",
                        to="carbone.foretclassee",
                        verbose_name="Foret classee",
                    ),
                ),
                (
                    "nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupations",
                        to="carbone.nomenclaturecouvert",
                        verbose_name="Type de couvert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupation du sol",
                "verbose_name_plural": "Occupations du sol",
                "ordering": ["annee", "foret", "nomenclature"],
                "indexes": [
                    models.Index(fields=["annee"], name="carbone_occ_annee_471256_idx"),
                    models.Index(
                        fields=["foret", "annee"], name="carbone_occ_foret_i_0096c1_idx"
                    ),
                    models.Index(
                        fields=["nomenclature", "annee"],
                        name="carbone_occ_nomencl_488d5e_idx",
                    ),
                    models.Index(
                        fields=["foret", "nomenclature", "annee"],
                        name="carbone_occ_foret_i_15707f_idx",
                    ),
                ],
            },
        ),
    ]
